---
title: "R-Preprocessing"
author: "Samya"
date: "12/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath("/Users/samyam/Documents/Samya/Insofe/insofe/day7/20181222_Batch56_CSE7212c_Lab03_Introduction_to_R-Preprocessing/Datasets"))
```

```{r}
rm(list = ls(all=TRUE))
```

```{r}
getwd()
```

```{r}
mtcars = read.csv(file = "mtcars.csv",header=TRUE,sep=",")
sum(is.na(mtcars))
class(mtcars)
head(mtcars)
```

```{r}
#na.strings - values that are to be interpreted as NA values
mtcars = read.csv(file = "mtcars.csv",header=TRUE,sep=",",na.strings = c("NA","?"))
sum(is.na(mtcars))
class(mtcars)
```

```{r}
head(mtcars)
```

```{r}
tail(mtcars)
```

```{r}
str(mtcars)
```

```{r}
colnames(mtcars)
```

```{r}
rownames(mtcars)
```

```{r}
dim(mtcars)
```

```{r}
mtcars$X
```

```{r}
rownames(mtcars) = mtcars$X
rownames(mtcars)
```

```{r}
mtcars
```

```{r}
mtcars$X=NULL
mtcars
```

```{r}
str(mtcars)
```

```{r}
colnames(mtcars)[6] = "weight"
```

```{r}
str(mtcars)
```

```{r}
colnames(mtcars)
```

```{r}
is.numeric(mtcars$mpg)
```

```{r}
is.numeric(mtcars$vs)
```

```{r}
is.character(mtcars$hp)
```

```{r}
is.factor(mtcars$vs)
```

```{r}
mtcars$cyl
```

```{r}
mtcars$cyl = as.factor(mtcars$cyl)
mtcars$am = as.factor(mtcars$am)

```

```{r}
mtcars$cyl
```

```{r}
str(mtcars)
```

```{r}
mtcars[,'carb']
```

```{r}
mtcars[,11]
```

```{r}
mtcars$carb
```

```{r}
mtcars[,c('mpg','carb')]
```

```{r}
mtcars[,c(1,11)]
```

```{r}
class(mtcars[,c('mpg','carb')])
```

```{r}
class(mtcars[,c(1,11)])
```

```{r}
rownames(mtcars)
```

```{r}
mtcars['Duster 360',]
```

```{r}
class(mtcars['Duster 360',])
```

```{r}
mtcars[7,]
```

```{r}
class(mtcars[7,])
```

```{r}
mtcars[c(6,7),]
```

```{r}
class(mtcars[c(6,7),])
```

```{r}
subset(mtcars,select=c(cyl,mpg))
```

```{r}
subset(mtcars,select=-c(cyl,mpg,disp))
```

```{r}
mtcars[c('Duster 360','Valiant'),c('mpg','hp')]
```

```{r}
class(mtcars[c('Duster 360','Valiant'),c('mpg','hp')])
```

```{r}
mtcars[c(6,7),c(1,2)]
```

```{r}
class(mtcars[c(6,7),c(1,2)])
```

```{r}
colsum=c()
for (i in colnames(mtcars))
{
  sum = 0
  for (j in mtcars[,i])
  {
    if(is.na(j)==TRUE)
    {
      sum = sum+1
    }else
    {
      sum = sum
    }
  }
  colsum[i] = sum
}

colsum
```

```{r}
class(colsum)
```

```{r}
colSums(is.na(mtcars))
```

```{r}
rowSums(is.na(mtcars))
```

```{r}
sum(is.na(mtcars))
```

```{r}
summary(mtcars)
```

```{r}
mtcars_new <- mtcars
dim(mtcars_new)
```

```{r}
sum(is.na(mtcars_new))
```

```{r}
mtcars_omit <- na.omit(mtcars_new)
dim(mtcars_omit)
```

```{r}
sum(is.na(mtcars_omit))
```

```{r}
#install.packages("DMwR")
library(DMwR)
```

```{r}
head(mtcars,15)
```

```{r}
summary(mtcars)
```

```{r}
mtcars_imputed  = centralImputation(mtcars)
colSums(is.na(mtcars_imputed))
```

```{r}
head(mtcars_imputed,15)
```

```{r}
mtcars_imputed$pwr <-mtcars_imputed$hp/mtcars_imputed$weight 
head(mtcars_imputed)
```

```{r}
centralvalue()
```

```{r}
#install.packages("infotheo")
library(infotheo)
```

```{r}
x <- c(5,6,7,8,8,9,10,11,11,20,21,22)
length(x)
```

```{r}
x0 <- discretize(x, disc = "equalfreq", nbins = 4)
table(x0)
```

```{r}
x1 <- discretize(x, disc = "equalwidth", nbins = 4)
table(x1)
```

```{r}
mtcars_imputed$hp
```

```{r}
# After looking the numbers we can get the idea of how to bin them 
bins = cut(mtcars_imputed$hp,breaks = seq(0,350,50),include.lowest = T,right = T)
bins
```

```{r}
table(bins)
```

```{r}
library(infotheo)
(nbins = floor(sqrt(NROW(mtcars_imputed $hp))))
```

```{r}
eq_wid_bin=discretize(mtcars_imputed $hp,disc = "equalwidth",nbins)
table(eq_wid_bin)
```

```{r}
eq_freq_bin<-discretize(mtcars_imputed $hp,disc = "equalfreq",nbins)
table(eq_freq_bin)
```

```{r}
str(mtcars_imputed)
```

```{r}
#install.packages("dummies")
library(dummies)
```

```{r}
mtcars_imputed$vs
```

```{r}
dummy(mtcars_imputed$vs)
```

```{r}
#install.packages("vegan")
library(vegan)
```

```{r}
mtcars_imputed_range <- decostand(x =mtcars_imputed[,c('mpg','disp','drat','weight','qsec','gear','carb')],method ="range",MARGIN = 2)
str(mtcars_imputed_range)
```

```{r}
range(mtcars_imputed_range$disp)
```

```{r}
head(mtcars_imputed_range)
```

```{r}
mtcars_imputed_standardized <- decostand(x =mtcars_imputed[,c('mpg','disp','drat','weight','qsec','gear','carb')],method ="standardize",MARGIN = 2)
range(mtcars_imputed_standardized$mpg)

```

```{r}
lapply(mtcars['mpg'],mean)
```

```{r}
lapply(mtcars_imputed_range,mean)
```

```{r}
class(lapply(mtcars_imputed_range,mean))
```

```{r}
class(lapply(mtcars['mpg'],mean))
```

```{r}
empty_list=list()
empty_list=lapply(mtcars_imputed_range,mean)
empty_list
```

```{r}
empty_list[1]
```

```{r}
sapply(mtcars_imputed_range['mpg'],max)
```

```{r}
class(sapply(mtcars_imputed_range['mpg'],max))
```

```{r}
sapply(mtcars_imputed_range,max)
```

```{r}
class(sapply(mtcars_imputed_range['mpg'],max))
```

```{r}
sapply_vec= sapply(mtcars_imputed_range,min)
sapply_vec
```

```{r}
str(mtcars_imputed)
```

```{r}
tapply(mtcars_imputed$weight, mtcars_imputed$am, mean)
```

```{r}
tapply(mtcars_imputed$weight, mtcars_imputed$cyl, median)
```

```{r}
class(tapply(mtcars_imputed$weight, mtcars_imputed$cyl, median))
```

```{r}
tapply(mtcars_imputed$weight, mtcars_imputed$vs, range)
```

```{r}
class(tapply(mtcars_imputed$weight, mtcars_imputed$vs, range))
```

```{r}
tapply(mtcars_imputed$weight, mtcars_imputed$drat, mean)
```

```{r}
tapply(mtcars$hp,mtcars$cyl,max)
```

```{r}
apply_mtcars=apply(mtcars_imputed_range[,-c(1)],2,max)
apply_mtcars
```

```{r}
class(apply(mtcars_imputed_range[,-c(1)],2,max))
```

```{r}
apply(mtcars_imputed_range,2,mean)
```

```{r}
#install.packages("openxlsx")
library(openxlsx)
```

```{r}
cust_bank_details = read.xlsx("Customer_Bank Details_MV.xlsx",sheet  = "Customer_Bank Details_MV")
cust_demographics = read.xlsx("Customer_Demographics_MV_DOB.xlsx",sheet = "Customer_Demographics_MV_DOB")
```

```{r}
head(cust_bank_details)
```

```{r}
head(cust_demographics)
```

```{r}
library(base)
```

```{r}
# Inner Join
IJ_merged_df <- merge(x = cust_bank_details,y = cust_demographics, by.x = "ID", by.y = "Customer.ID")
```

```{r}
IJ_merged_df
```

```{r}
View(IJ_merged_df)
```

```{r}
head(IJ_merged_df)
```

```{r}
#Left Outer Join
LoJ_merged_df = merge(x = cust_bank_details, y = cust_demographics,  by.x = "ID", by.y = "Customer.ID", all.x = TRUE)
  
#Right Outer Join
RoJ_merged_df <- merge(x = cust_bank_details, y = cust_demographics,  by.x = "ID", by.y = "Customer.ID", all.y = TRUE)

#Full Outer Join
FoJ_merged_df <- merge(x = cust_bank_details, y = cust_demographics,  by.x = "ID", by.y = "Customer.ID", all = TRUE)

```

```{r}
# While creating a vector, if we want to create elements randomly, we use sample function
A<-sample(x = 1:10,size = 20,replace = T)
A
```

```{r}
# Function to get the size of a vector-length
length(A)
```

```{r}
# In some cases, as in sample with replace=T, the elements may repeat, To get the unique elements
unique(A)
```

```{r}
class(unique(A))
```

```{r}
# To get how many unique elements are in A
length(unique(A))

```

```{r}
# We have a dataframe DF and we want to know the dimensions of it
# dim(DF)
dim(mtcars)
```

```{r}
# To get the number of rows and number of columns of DF-nrow and ncol respectively
nrow(mtcars)
```

```{r}
ncol(mtcars)
```

```{r}
ls()
```

```{r}
rm(list=c("A","apply_mtcars"))
ls()
```

```{r}
rm(list=ls())
ls()
```

```{r}
# txt and tsv
Data<-read.table("SampleData.txt",header=T,sep="\t") 
Data
```

```{r}
write.table(Data,"Data2.txt",row.names=T,sep="\t")
```

```{r}
write.table(Data,"Data3.tsv",row.names=F)
A<-read.table("Data3.tsv",header=T)
A
```

```{r}
data("iris")
iris_df=iris
head(iris_df,10)
```

```{r}
write.csv(iris_df,file="iris_df.csv",row.names = FALSE)
```

```{r}

```

```{r}

```

```{r}

```
